# Generated by Django 5.1.6 on 2025-03-03 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "permissions": [
                    ("can_create_category", "Can Create Category"),
                    ("can_update_category", "Can Update Category"),
                    ("can_view_category", "Can View Category"),
                    ("can_delete_category", "Can Delete Category"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_create_blog", "Can Create Blog"),
                    ("can_update_blog", "Can Update Blog"),
                    ("can_view_blog", "Can View Blog"),
                    ("can_delete_blog", "Can Delete Blog"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_create_product", "Can Create Product"),
                    ("can_update_product", "Can Update Product"),
                    ("can_view_product", "Can View Product"),
                    ("can_delete_product", "Can Delete Product"),
                ],
            },
        ),
    ]
